import "./globals.css";
import { Comfortaa } from "next/font/google";

const inter = Comfortaa({ subsets: ["latin"] });

export const metadata = {
  title: "consciousleap",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
