import React from "react";

const Policies = () => {
  return (
    <div className="px-[8vw] py-[2vw]">
      <h1 className="text-3xl font-bold mb-4">Privacy Policy Page</h1>
      <p>
        This Privacy Policy describes our policies and procedures on collecting,
        using, anddisclosing your information when you use the service and tells
        you about your privacy rights and how the law protects you.
      </p>
      <p className="mt-0">
        We use your personal data to provide and improve the service. By using
        the service, you agree to this Privacy Policy&apos;s collection and use
        of information.
      </p>
      <h1 className="underline font-bold">Interpretation and Definitions</h1>
      <div>
        <h1 className="font-bold">Interpretation:</h1>
        <p>
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions
          shall have the same meaning regardless of whether they appear singular
          or plural.
        </p>
      </div>
      <div>
        <h1 className="font-bold">Definitions:</h1>
        <p>For this Privacy Policy:</p>
        <p>
          <b className="font-bold">Account</b> means an individual account
          created for your access or parts of our service.
          <br /> <b className="font-bold">Affiliate</b> means an entity that
          controls is controlled by or is under common control with a party,
          where &quot;control&quot;means ownership of 50% or more of the shares,
          equity interest, or other securities entitled to vote for the election
          of directors or other managing authority.
          <br /> <b className="font-bold">Company</b> (referred to as either
          &quot;the Company,&quot; &quot;We,&quot; &quot;Us,&quot;or
          &quot;Our&quot;in this Agreement) refers to Private Limited Company,
          Järvevana Tee 9, Tallinn, 11314,Estonia.
          <br /> <b className="font-bold">Cookies</b> are small files placed on
          your computer, mobile device, or any other device by a website,
          containing the details of your browsing history on that website among
          its many uses.
          <br /> <b className="font-bold">The country</b> refers to Estonia.
          <br /> Device means any device that can access the service, such as a
          computer, a cellphone, or a digital tablet.
          <br /> <b className="font-bold">Personal Data</b> is any information
          that relates to an identified or identifiable individual.
          <br /> <b className="font-bold">Service</b> refers to the Website.
          <br /> <b className="font-bold">Service Provider</b> means any natural
          or legal person who processes the data on behalf of the Company. It
          refers to third-party companies or individuals employed by the Company
          to facilitate the service, to provide the service on behalf of the
          Company, to perform services related to the service, or to assist the
          Company in analyzing how the service is used.
          <br /> <b className="font-bold">Third-party Social Media Service</b>
          refers to any website or any social networkwebsite through which a
          user can log in or create an account to use the service.
          <br />
          <b className="font-bold">Usage Data</b> refers to data collected
          automatically, either generated by the use of the service or from the
          service infrastructure itself (for example, the duration of a page
          visit).
          <br /> <b className="font-bold">The website</b> refers to
          consciousleap, accessible from http://www.consciousleap.co.
          <br /> <b className="font-bold">You</b> mean the individual accessing
          or using the service, the company, or other legal entity on behalf of
          which such individual is accessing or using the service, as
          applicable.
        </p>
        <p className="font-bold underline mt-7">
          Collecting and Using Your Data
        </p>
        <p className="font-bold">Types of Data Collected</p>
        <p className="font-bold">Personal Data:</p>
        <p>
          While using our service, we may ask you to provide us with certain
          personally identifiable information that can be used to contact or
          identify you. Personally identifiable information may include, but is
          not limited to:
        </p>
        <ol className="list-decimal ml-8">
          <li>Email address </li>
          <li>First name and last name </li>
          <li>Phone number </li>
          <li>Address, State,</li>
          <li>Province, ZIP/ Postal code, City </li>
          <li>Usage Data</li>
        </ol>
        <h1 className="mt-5 font-bold">Usage Data:</h1>
        <p className="-mt-4">
          Usage Data is collected automatically when using the service.
          <br /> Usage Data may include information such as your device&apos;s
          internet protocol address (e.g., IP address), browser type, browser
          version, the pages of our service that you visit, the time and date of
          your visit, the time spent on those pages, unique device identifiers
          and other diagnostic data.
          <br /> When you access the service by or through a mobile device, We
          may collect certain information automatically, including, but not
          limited to, the type of mobile device you use, your mobile
          device&apos;s unique ID, the IP address of your mobile device, your
          mobile operating system, the type of mobile Internet browser you use,
          unique device identifiers and other diagnostic data.
          <br /> We may also collect information your browser sends whenever you
          visit our service or access the service through a mobile device.
        </p>
        <h1 className="font-bold">
          Information from Third-Party Social Media Services:
        </h1>
        <p className="-mt-5">
          The Company allows you to create an account and log in to use the
          service through the following third-party social media services:
        </p>
        <ol className="list-decimal ml-8">
          <li>Google</li>
          <li>Facebook</li>
          <li>Twitter</li>
          <li>Linkedin</li>
        </ol>
        <p className="my-5">
          Suppose you register through or otherwise grant us access to a
          third-party social media service. In that case, We may collect
          personal data associated with your thirdparty social media
          service&apos;s account, such as your name, email address, activities,
          or contact list associated with that account.
          <br /> You may also share additional information with the Company
          through your third-party social media service&apos;s account. Suppose
          you provide such information and personal data during registration or
          otherwise. In that case, you are giving the Company permission to use,
          share, and store it in a manner consistent with this Privacy Policy.
        </p>
      </div>
      <div>
        <h1 className="font-bold">Tracking Technologies and Cookies:</h1>
        <p className="-mt-5">
          Tracking technologies are beacons, tags, and scripts to collect and
          track information and improve and analyze our service. We use Cookies
          and similar tracking technologies to track the activity on our service
          and store certain information. The technologies we use may include:
        </p>
        <p className="mt-7">
          <b>Cookies or Browser Cookies</b>. A cookie is a small file placed on
          your device. You can instruct your browser to refuse all Cookies or to
          indicate when a cookie is being sent. However, if you do not accept
          Cookies, You may be unable to use some parts of our service. Unless
          you have adjusted your browser setting so that it will refuse cookies,
          our service may use Cookies. <br />
          <b>Web Beacons</b>. Certain sections of our service and our emails may
          contain small electronic files known as web beacons (also referred to
          as clear gifs, pixel tags, and single-pixel gifs) that permit the
          Company, for example, to count users who have visited those pages or
          opened an email and for other related website statistics (for example,
          recording the popularity of a specific section and verifying system
          and server integrity).
        </p>
        <p className="mt-6">
          Cookies can be &quot;Persistent&quot;or &quot;Session&quot;Cookies.
          Persistent Cookies remain on your personal computer or mobile device
          when you go offline, while Session Cookies are deleted as soon as you
          close your web browser.
          <br /> We use both Session and Persistent Cookies for the purposes set
          out below:
        </p>
        <h1 className="underline font-bold">Necessary / Essential Cookies</h1>
      </div>
    </div>
  );
};

export default Policies;
