import React from "react";

const Policies = () => {
  return (
    <div className="px-5 md:px-[2vw] md:py-[1vw] py-[2vw] privacy">
      <h1 className="text-3xl font-bold mb-4 text-websiteBlue">
        Privacy Policy Page
      </h1>
      <div className=" px-2 md:px-4">
        <p>
          This Privacy Policy describes our policies and procedures on
          collecting, using, anddisclosing your information when you use the
          service and tells you about your privacy rights and how the law
          protects you.
        </p>
        <p className="mt-0">
          We use your personal data to provide and improve the service. By using
          the service, you agree to this Privacy Policy&apos;s collection and
          use of information.
        </p>
        <h1 className="underline font-bold text-lg">
          Interpretation and Definitions
        </h1>
        <div>
          <h3 className="font-bold text-lg">Interpretation:</h3>
          <p>
            The words of which the initial letter is capitalized have meanings
            defined under the following conditions. The following definitions
            shall have the same meaning regardless of whether they appear
            singular or plural.
          </p>
        </div>
        <div>
          <h3 className="font-bold text-lg">Definitions:</h3>
          <p>For this Privacy Policy:</p>
          <p>
            <b className="font-bold">Account</b> means an individual account
            created for your access or parts of our service.
            <br /> <b className="font-bold">Affiliate</b> means an entity that
            controls is controlled by or is under common control with a party,
            where &quot;control&quot;means ownership of 50% or more of the
            shares, equity interest, or other securities entitled to vote for
            the election of directors or other managing authority.
            <br /> <b className="font-bold">Company</b> (referred to as either
            &quot;the Company,&quot; &quot;We,&quot; &quot;Us,&quot;or
            &quot;Our&quot;in this Agreement) refers to Private Limited Company,
            Järvevana Tee 9, Tallinn, 11314,Estonia.
            <br /> <b className="font-bold">Cookies</b> are small files placed
            on your computer, mobile device, or any other device by a website,
            containing the details of your browsing history on that website
            among its many uses.
            <br /> <b className="font-bold">The country</b> refers to Estonia.
            <br /> Device means any device that can access the service, such as
            a computer, a cellphone, or a digital tablet.
            <br /> <b className="font-bold">Personal Data</b> is any information
            that relates to an identified or identifiable individual.
            <br /> <b className="font-bold">Service</b> refers to the Website.
            <br /> <b className="font-bold">Service Provider</b> means any
            natural or legal person who processes the data on behalf of the
            Company. It refers to third-party companies or individuals employed
            by the Company to facilitate the service, to provide the service on
            behalf of the Company, to perform services related to the service,
            or to assist the Company in analyzing how the service is used.
            <br /> <b className="font-bold">Third-party Social Media Service</b>
            refers to any website or any social networkwebsite through which a
            user can log in or create an account to use the service.
            <br />
            <b className="font-bold">Usage Data</b> refers to data collected
            automatically, either generated by the use of the service or from
            the service infrastructure itself (for example, the duration of a
            page visit).
            <br /> <b className="font-bold">The website</b> refers to
            consciousleap, accessible from http://www.consciousleap.co.
            <br /> <b className="font-bold">You</b> mean the individual
            accessing or using the service, the company, or other legal entity
            on behalf of which such individual is accessing or using the
            service, as applicable.
          </p>
          <p className="font-bold underline mt-7">
            Collecting and Using Your Data
          </p>
          <p className="font-bold">Types of Data Collected</p>
          <p className="font-bold">Personal Data:</p>
          <p>
            While using our service, we may ask you to provide us with certain
            personally identifiable information that can be used to contact or
            identify you. Personally identifiable information may include, but
            is not limited to:
          </p>
          <ol className="list-decimal ml-8">
            <li>Email address </li>
            <li>First name and last name </li>
            <li>Phone number </li>
            <li>Address, State,</li>
            <li>Province, ZIP/ Postal code, City </li>
            <li>Usage Data</li>
          </ol>
          <h3 className="mt-5 font-bold text-lg">Usage Data:</h3>
          <p className="">
            Usage Data is collected automatically when using the service.
            <br /> Usage Data may include information such as your device&apos;s
            internet protocol address (e.g., IP address), browser type, browser
            version, the pages of our service that you visit, the time and date
            of your visit, the time spent on those pages, unique device
            identifiers and other diagnostic data.
            <br /> When you access the service by or through a mobile device, We
            may collect certain information automatically, including, but not
            limited to, the type of mobile device you use, your mobile
            device&apos;s unique ID, the IP address of your mobile device, your
            mobile operating system, the type of mobile Internet browser you
            use, unique device identifiers and other diagnostic data.
            <br /> We may also collect information your browser sends whenever
            you visit our service or access the service through a mobile device.
          </p>
          <h3 className="font-bold">
            Information from Third-Party Social Media Services:
          </h3>
          <p className="">
            The Company allows you to create an account and log in to use the
            service through the following third-party social media services:
          </p>
          <ol className="list-decimal ml-8">
            <li>Google</li>
            <li>Facebook</li>
            <li>Twitter</li>
            <li>Linkedin</li>
          </ol>
          <p className="my-5">
            Suppose you register through or otherwise grant us access to a
            third-party social media service. In that case, We may collect
            personal data associated with your thirdparty social media
            service&apos;s account, such as your name, email address,
            activities, or contact list associated with that account.
            <br /> You may also share additional information with the Company
            through your third-party social media service&apos;s account.
            Suppose you provide such information and personal data during
            registration or otherwise. In that case, you are giving the Company
            permission to use, share, and store it in a manner consistent with
            this Privacy Policy.
          </p>
        </div>
        <div>
          <h1 className="font-bold">Tracking Technologies and Cookies:</h1>
          <p className="">
            Tracking technologies are beacons, tags, and scripts to collect and
            track information and improve and analyze our service. We use
            Cookies and similar tracking technologies to track the activity on
            our service and store certain information. The technologies we use
            may include:
          </p>
          <p className="mt-7">
            <b>Cookies or Browser Cookies</b>. A cookie is a small file placed
            on your device. You can instruct your browser to refuse all Cookies
            or to indicate when a cookie is being sent. However, if you do not
            accept Cookies, You may be unable to use some parts of our service.
            Unless you have adjusted your browser setting so that it will refuse
            cookies, our service may use Cookies. <br />
            <b>Web Beacons</b>. Certain sections of our service and our emails
            may contain small electronic files known as web beacons (also
            referred to as clear gifs, pixel tags, and single-pixel gifs) that
            permit the Company, for example, to count users who have visited
            those pages or opened an email and for other related website
            statistics (for example, recording the popularity of a specific
            section and verifying system and server integrity).
          </p>
          <p className="mt-6">
            Cookies can be &quot;Persistent&quot;or &quot;Session&quot;Cookies.
            Persistent Cookies remain on your personal computer or mobile device
            when you go offline, while Session Cookies are deleted as soon as
            you close your web browser.
            <br /> We use both Session and Persistent Cookies for the purposes
            set out below:
          </p>
          <h3 className="underline font-bold">Necessary / Essential Cookies</h3>
        </div>
        <p>
          <b>Type</b>: Session Cookies
        </p>

        <p>
          <b>Administered by</b>: Us
        </p>

        <p>
          <b>Purpose</b>: These Cookies are essential to provide you with
          services available through the Website and to enable you to use some
          of its features. They help to authenticate users and prevent
          fraudulent use of user accounts. Without these Cookies, the services
          you have asked for cannot be provided, and We only use these Cookies
          to provide you with those services.
        </p>
        <br />
        <p className="underline font-bold">
          Cookies Policy / Notice Acceptance Cookies
        </p>

        <p>
          <b>Type</b>: Persistent Cookies
        </p>

        <p>
          <b>Administered by</b>: Us
        </p>

        <p>
          <b>Purpose</b>: These Cookies identify if users have accepted cookies
          on the Website.
        </p>

        <p></p>
        <br />

        <p className="font-bold underline">Functionality Cookies</p>

        <p>Type: Persistent Cookies</p>

        <p>Administered by: Us</p>

        <p>
          Purpose: These Cookies allow us to remember choices you make when you
          use the Website, such as remembering your login details or language
          preference. The purpose of these Cookies is to provide you with a more
          personal experience and avoid re-entering your preferences every time
          you use the Website.
        </p>

        <p>
          For more information about the cookies we use and your choices
          regarding cookies, please visit our Cookies Policy or the Cookies
          section of our Privacy Policy.
        </p>

        <p></p>
        <br />

        <p className="font-bold underline">Use of Your Data</p>

        <p>The Company may use Personal Data for the following purposes:</p>

        <p>
          To provide and maintain our Service, including monitoring the usage of
          our
        </p>

        <p>service.</p>

        <p>
          To manage Your Account: to manage your registration as a service user.
          Your Data can give you access to different Service functionalities as
          a registered user.
        </p>

        <p>
          For the performance of a contract: the development, compliance, and
          undertaking of the purchase contract for the products, items, or
          services you have purchased or any other agreement with us through the
          service.
        </p>

        <p>
          To contact You: To contact you by email, telephone calls, SMS, or
          other equivalent forms of electronic communication, such as a mobile
          application&apos;s push notifications regarding updates or informative
          communications related to the functionalities, products, or contracted
          services, including the security updates, when necessary or reasonable
          for their implementation.
        </p>

        <p>
          To provide You with news, special offers, and general information
          about other goods, services, and events we offer similar to those you
          have already purchased or enquired about unless you have opted not to
          receive such information.
        </p>

        <p>
          To manage Your requests: To attend to and manage your requests to us.
        </p>

        <p>
          For business transfers: We may use your information to evaluate or
          conduct a merger, divestiture, restructuring, reorganization,
          dissolution, or other sale or transfer of some or all of our assets,
          whether as a going concern or as part of bankruptcy, liquidation, or
          similar proceeding, in which Personal Data held by us about our
          service users is among the assets transferred.
        </p>

        <p>
          For other purposes: We may use your information for other purposes,
          such as data analysis, identifying usage trends, determining the
          effectiveness of our promotional campaigns, and evaluating and
          improving our service, products, services, marketing, and your
          experience.
        </p>

        <p>
          We may share your personal information in the following situations:
        </p>

        <p>
          With Service Providers: We may share your personal information with
          service providers to monitor and analyze the use of our service to
          contact you.
          <br />
          For business transfers: We may share or transfer your personal
          information in connection with, or during negotiations of, any merger,
          sale of Company assets, financing, or acquisition of all or a portion
          of our business to another company.
          <br />
          With Affiliates: We may share your information with our affiliates, in
          which case we will require those affiliates to honor this Privacy
          Policy. Affiliates include our parent company and any other
          subsidiaries, joint venture partners, or companies we control or are
          under common control.
          <br />
          With business partners: We may share your information with our
          business partners to offer you certain products, services, or
          promotions.
          <br />
          With other users: When you share personal information or otherwise
          interact in public areas with other users, such information may be
          viewed by all users and may be publicly distributed outside. If you
          interact with other users or register through a third-party social
          media service, Your contacts on the third-party social media service
          may see your name, profile, pictures, and description of your
          activity. Similarly, other users can view your activity reports,
          communicate with you and view your profile.
          <br />
          With Your consent: We may disclose your personal information for any
          other purpose with your consent.
        </p>

        <br />
        <p className="font-bold underline">Retention of Your Data</p>

        <p>
          The Company will retain your Data only for as long as is necessary for
          the purposes set out in this Privacy Policy. We will retain and use
          your Data to the extent necessary to comply with our legal obligations
          (for example, if we are required to retain your data to comply with
          applicable laws), resolve disputes, and enforce our legal agreements
          and policies.
        </p>

        <p>
          The Company will also retain Usage Data for internal analysis
          purposes. Usage Data is generally kept for a shorter period, except
          when this data is used to strengthen the security or improve the
          functionality of our service, or we are legally obligated to retain
          this data for more extended periods.
        </p>

        <p></p>
        <br />

        <p className="font-bold underline">Transfer of Your Data</p>

        <p>
          Your information, including Personal Data, is processed at the
          Company&apos;s operating offices and in any other places where the
          parties involved in the processing are located. This information may
          be transferred to &mdash; and maintained on &mdash; computers outside
          your state, province, country, or other governmental jurisdiction
          where the data protection laws may differ from those from your
          jurisdiction.
        </p>

        <p>
          Your consent to this Privacy Policy, followed by submitting such
          information, represents your agreement to that transfer.
        </p>

        <p>
          The Company will take all steps reasonably necessary to ensure that
          your data is treated securely and by this Privacy Policy, and no
          transfer of your Personal Data will take place to an organization or a
          country unless there are adequate controls in place, including the
          security of your data and other personal information.
        </p>

        <p></p>
        <br />

        <p className="font-bold underline">Delete Your Data</p>

        <p>
          You have the right to delete or request that we assist in deleting the
          Personal Data we collected about you.
        </p>

        <p>
          Our service may allow you to delete certain information about you from
          within the service.
        </p>

        <p>
          You may update, amend, or delete your information anytime by signing
          in to your account if you have one and visiting the account settings
          section that allows you to manage your personal information. You may
          also contact us to request access to, correct, or delete any personal
          information you provided.
        </p>

        <p>
          Please note, however, that we may need to retain certain information
          when we have a legal obligation or lawful basis to do so.
        </p>

        <p></p>
        <br />
        <p className="underline font-bold">Disclosure of Your Data</p>

        <p></p>

        <b>Business Transactions:</b>

        <p>
          Your Data may be transferred if the Company is involved in a merger,
          acquisition, or asset sale.
        </p>

        <p className="font-bold">Law enforcement:</p>

        <p>
          Under certain circumstances, the Company may be required to disclose
          your Data if required to do so by law or in response to valid requests
          by public authorities (e.g., a court or a government agency).
        </p>

        <p>Other legal requirements</p>

        <p>
          The Company may disclose your data in the good faith belief that such
          action is necessary to:
        </p>

        <p className="ml-4">
          1. Comply with a legal obligation
          <br />
          2. Protect and defend the rights or property of the Company
          <br />
          3. Prevent or investigate possible wrongdoing in connection with the
          service
          <br />
          4. Protect the personal safety of users of the Service or the public
          <br />
          5. Protect against legal liability
        </p>

        <br />
        <p className="font-bold underline">Security of Your Data</p>

        <p>
          The security of your Personal Data is important to us, but remember
          that no method of transmission over the Internet or method of
          electronic storage is 100% secure. While we strive to use commercially
          acceptable means to protect your Personal Data, we cannot guarantee
          its absolute security.
        </p>

        <br />
        <p></p>

        <p className="underline font-bold">Children&apos;s Privacy</p>

        <p>
          Our service only addresses people under the age of 12. We do not
          knowingly collect personally identifiable information from anyone
          under 12. We may become aware that we have collected Personal Data
          from anyone under the age of 12 without verification of parental
          consent. In that case, we remove that information from our servers. If
          you are a parent or guardian and know that your child has provided us
          with Personal Data, please get in touch with us.
        </p>

        <p>
          If we rely on consent as a legal basis for processing your information
          and your country requires permission from a parent, We may need your
          parent&apos;s consent before we collect and use that information.
        </p>

        <br />
        <p></p>

        <p className="font-bold underline">Links to Other Websites</p>

        <p>
          Our Service may contain links to other websites that we do not
          operate. If you click on a third-party link, you will be directed to
          that third-party&apos;s site. We strongly advise you to review every
          site&apos;s privacy policy.
        </p>

        <p>
          We have no control over and assume no responsibility for third-party
          sites or services&apos; content, privacy policies, or practices.
        </p>

        <p></p>
        <br />

        <p className="underline font-bold">Changes to this Privacy Policy</p>

        <p>
          We may update our Privacy Policy from time to time. We will notify you
          of any changes by posting the new Privacy Policy on this page.
        </p>

        <p>
          We will inform you via email and a prominent notice on our service
          before the change becomes effective and update the &quot;Last
          updated&quot; date at the top of this Privacy Policy.
        </p>

        <p>
          You are advised to review this Privacy Policy periodically for any
          changes. Changes to this Privacy Policy are effective when posted on
          this page.
        </p>

        <p></p>
        <br />
        <p className="font-bold underline">Contact Us</p>

        <p>
          If you have any questions about this Privacy Policy, you can contact
          us:
        </p>

        <p>
          <b>By email</b>: support@consciousleap.co
        </p>

        <p>
          <b>By visiting this page on our website</b>:
          http://www.consciousleap.co
        </p>
      </div>
    </div>
  );
};

export default Policies;
